### ISSUE TITLE
not able to change colormap in Matlab R2018b

### ISSUE THREAD

**Issue by ZhsChen** [tsumpf/arrShow#9]
I am using arrShow in Matlab R2018b, and the colormap does not change after I choose one colormap different than the current one in the View->Colormap menu. Has anybody encountered the same problem?

**Comment by tsumpf** [comment]
Hi ZhsChen. Thanks your comment. Happy to hear from people using the tool. However, I wrote most of the parts during my PhD more than three years ago. And since my current employer uses different programming languages, I don't have access to Matlab anymore :-/
Yet it may be that srapacchi faced the same issue in his fork. At least he added something that looks like a fix in:
https://github.com/srapacchi/arrShow
Maybe this works for you as well?
If it does, it would be awesome if someone could confirm downward compatibility... and send me a pull request :-D

**Comment by tijlvdv** [comment]
I've tested srapacchi's fix in R2016b and R2018b. Updating the colormap works in both versions.

**Comment by tsumpf** [comment]
Thanks for the test! I'll try to contact Stanislas regarding a pull request :)
